import { javascript as eslint_config_sukka_js } from '../src/modules/javascript';

import ts_eslint_plugin from '@typescript-eslint/eslint-plugin';
import type { Linter } from 'eslint';

import fs from 'node:fs';
import path from 'node:path';

const DISABLED_RULES = new Set([
  'no-redeclare',
  'no-dupe-class-members'
]);

/**
 * typescript-eslint rules that still extends from ESLint core rules, yet deprecated
 * since ESLint core now supports the same functionality/syntax
 *
 * Those rules do not replace ESLint core rules anymore.
 */
const TS_ESLINT_EXTENSION_RULES_REPLACED_BY_BASE_RULE = new Set([
  // the base rule is recommended by typescript-eslint instead
  'no-loss-of-precision',
  // deprecated in typescript-eslint 8.64.0, core rule handles TS syntax since ESLint 10.8.0
  'no-loop-func',
  // deprecated, the core rule now supports `allowTypeImports`
  'no-restricted-imports'
]);

(async () => {
  const { default: stringifyObject } = await import('stringify-object');

  const TS_ESLINT_BASE_RULES_TO_BE_OVERRIDDEN = new Map<string, string>(
    Object.entries(ts_eslint_plugin.rules)
      // https://github.com/sweepline/eslint-plugin-unused-imports/blob/2563edf7d7894e0cc05163d9e9180bc3c56471cc/lib/rules/no-unused-imports.js#L15
      .reduce<Array<[baseRuleName: string, ruleName: string]>>((acc, [ruleName, rule]) => {
        if (
          'meta' in rule
          && 'docs' in rule.meta && typeof rule.meta.docs === 'object'
          && 'extendsBaseRule' in rule.meta.docs
          && rule.meta.docs.extendsBaseRule != null
          && !TS_ESLINT_EXTENSION_RULES_REPLACED_BY_BASE_RULE.has(ruleName)
        ) {
          acc.push([
            typeof rule.meta.docs.extendsBaseRule === 'string'
              ? rule.meta.docs.extendsBaseRule
              : ruleName,
            ruleName
          ]);
        }
        return acc;
      }, [])
  );

  const rules = Object.entries(
    (await eslint_config_sukka_js())
      .reduce((acc, cur) => ({ ...acc, ...cur.rules }), {})
  )
    // .filter(([, value]) => {
    //   if (typeof value === 'string') {
    //     return value !== 'off';
    //   }
    //   if (typeof value === 'number') {
    //     return value !== 0;
    //   }
    //   if (Array.isArray(value)) {
    //     return value.length !== 0 && value[0] !== 'off';
    //   }
    //   return true;
    // })
    .reduce<Linter.RulesRecord>((acc, [baseRuleName, value]) => {
      switch (baseRuleName) {
        case 'camelcase': {
          // disable camelcase directly, use custom @typescript-eslint/naming-convention instead

          acc[baseRuleName] = 'off';

          break;
        }
        case 'sukka/no-return-await': {
          // the extension rule is named differently from the base rule, so the
          // `extendsBaseRule` map above cannot pair them up automatically
          acc[baseRuleName] = 'off';
          acc['@typescript-eslint/return-await'] = ['error', 'in-try-catch'];

          break;
        }
        // Rules in TS_ESLINT_EXTENSION_RULES_REPLACED_BY_BASE_RULE need no case here:
        // they were filtered out of the map, so this branch simply leaves them alone.
        default: if (TS_ESLINT_BASE_RULES_TO_BE_OVERRIDDEN.has(baseRuleName)) {
          const replacementRulename = TS_ESLINT_BASE_RULES_TO_BE_OVERRIDDEN.get(baseRuleName)!;
          acc[baseRuleName] = 'off';
          acc[`@typescript-eslint/${replacementRulename}`] = DISABLED_RULES.has(baseRuleName) ? 'off' : value;
        }
      }
      return acc;
    }, {});

  fs.writeFileSync(
    path.resolve(__dirname, '../src/modules/_generated_typescript_overrides.ts'),
    [
      '// This file is generated by scripts/codegen.ts',
      '// DO NOT EDIT THIS FILE MANUALLY',
      'import type { SukkaESLintRuleConfig } from \'@eslint-sukka/shared\';',
      '',
      'export const generated_typescript_overrides: SukkaESLintRuleConfig = {',
      `  rules: ${stringifyObject(rules, { indent: '  ', singleQuotes: true }).split('\n').map((line) => `  ${line}`).join('\n').trimStart()}`,
      '};',
      ''
    ].join('\n')
  );
})();
